### ISSUE TITLE
Switch Fluid Pipe don't work

### ISSUE THREAD

**Issue by TheEska** [tcooc/AdditionalPipesBC#108]
the pipes connect but nothing flows through
it doesn't work on multiplay (server: Cauldron-MCP-Plus version 1.7.10-1.1240.06.213 API R0.1-Snapshot) and on singleplayer.

it gives no error or exceptions

Mod list:

AdditionalPipes 4.0
AdvancedSolarPanel 3.5.1
Appliedenergistics2 rv1 stable 1
Buildcraft 6.3.6
BuildcraftAdditions 2.0
ChickenChunks 1.3.4.16-universal
CodeChickenCore 1.0.4.29-universal
CoFHCore 3.0.0B9-40
IndustrialCraft 2.2.658 experimental
logisticsPipes 0.8.3.100
MineFactoryReloaded 2.8.0 RC6-5
NetherOres 2.3.0RC4-4
PowerConverters 3.0.3.40
Railcraft 9.4.0.0

![2015-02-15_08 51 41](https://cloud.githubusercontent.com/assets/11014044/6202512/4b957ee2-b4f0-11e4-85d3-22cdaccb277f.png)

**Comment by multiplemonomials** [comment]
Should be fixed in latest release.  Thanks for your time.
