### ISSUE TITLE
Buildcraft 6.4 Beta Long distance not working

### ISSUE THREAD

**Issue by kremsy** [tcooc/AdditionalPipesBC#109]
I installed today the Additional Pipes mode on my Buildcraft server which is running Buildcraft 6.4 Beta. I made a test of the teleportation pipe, they worked when they just were 2 blocks appart from eachother, than I tried 300: the source sends the items, but they never get received at the destination.

**Comment by kremsy** [comment]
More investigation showed that it works until im next to the quarry, when I move away from the quarry, after about 30seconds, no items appear at the receive point. Im wondering if i make something wrong, if it is a problem of the plugin or if chunkloading of buildcraft has a bug.

**Comment by multiplemonomials** [comment]
What type of chunkloader are you using?

**Comment by kremsy** [comment]
Problem solved, the quarries got built in an Buildcraft 6.3.x version when the quarry chunkloading was broken. Rebuilding the quarrie solved the bugs.
