### ISSUE TITLE
crash adv wodden pipe

### ISSUE THREAD

**Issue by wi-ta** [tcooc/AdditionalPipesBC#110]
Heya  multiplemonomials
i hope this is the right place :-)

Every time i try to use the butten in the GUI i get this error on the server.
http://212.227.55.252/crash.txt

grets
Wi-ta

**Comment by wi-ta** [comment]
ups did forget to say
i did have this in older release also so i did make a new server (root server  win 2012 not local)

MC Version: 1.7.10
Forge Version: 10.13.2.1291 (in 1230 i hade this also)
BC Version 6.4.0 (in 6.3.X i had this also)
additionalpipes Version: 4.1(in3.x i had this also)

**Comment by wi-ta** [comment]
dammit wrong butten hehe

**Comment by multiplemonomials** [comment]
Can you check if it's fixed in the latest release?

**Comment by wi-ta** [comment]
Hi multiplemonomials
i can confirm the problem is gone.
Working very well now.

Thank you for your very good work.
