### ISSUE TITLE
Web Site ?

### ISSUE THREAD

**Issue by wi-ta** [tcooc/AdditionalPipesBC#111]
Hi multiplemonomials

How about a simple website (Google Sites maybe) for AdditionalPipesBC ?
I would like to do this if you dont mind.

gr.
Wi-Ta

**Comment by multiplemonomials** [comment]
I was thinking just a forum thread, or do you think that's not enough?

**Comment by wi-ta** [comment]
Forum is not a bad idea but it can get lost if older.
I was thinkig to show some pic how to use the AP, the Recipes, were to download.
Is there a Texturepack ?
I did not found a working one.

**Comment by multiplemonomials** [comment]
This one should work: http://bdcraft.net/community/pbdc-patches-rel/additional-pipes-3u42-t188.html

**Comment by wi-ta** [comment]
Unfortunely not working and messing up all other pipes.

**Comment by multiplemonomials** [comment]
Actually, I just checked myself, and this texture pack (the 128x version for MC1.6.4) works fine with Additional Pipes.  How were you installing it?

**Comment by wi-ta** [comment]
.minecraft\resourcepacks
just like all other
but this on first

**Comment by multiplemonomials** [comment]
You dragged the files from the texture patch into your main resource pack, right?  Just making sure you installed it right since I can't reproduce it.

**Comment by multiplemonomials** [comment]
Thread created [here](http://mod-buildcraft.com/forums/showthread.php?tid=1467), request closed :)
