### ISSUE TITLE
Switch owner's to using UUID

### ISSUE THREAD

**Issue by 61352151511** [tcooc/AdditionalPipesBC#112]
https://github.com/tcooc/AdditionalPipesBC/blob/master/src/main/java/buildcraft/additionalpipes/pipes/PipeTeleport.java

The owner is kept track of by using the name, if someone were to change their MC username now they would no longer be considered the owner. It should be switched to using UUID's

**Comment by multiplemonomials** [comment]
Can you confirm that this is fixed in the latest release?

**Comment by 61352151511** [comment]
I can not, as I changed my name recently so can't test because of the name changing limit, however if anyone else reading this issue wants to change their name, they should place a teleport pipe first ;)
