### ISSUE TITLE
Teleport and LP

### ISSUE THREAD

**Issue by LuqxUnknow** [tcooc/AdditionalPipesBC#117]
logistic pipes does not connect with teleport pipe

![2015-05-31_23 41 03](https://cloud.githubusercontent.com/assets/12689560/7905437/0cf43a82-07ef-11e5-802a-1ad4415b4a7d.png)

additionalpipes-4.4.0
buildcraft-6.4.11
logisticspipes-0.8.3.117

please help me,

thx.

**Comment by multiplemonomials** [comment]
Thanks for reporting, but this is a known issue.  See https://github.com/RS485/LogisticsPipes/issues/348
