### ISSUE TITLE
Crash Encountered an unexpected exception

### ISSUE THREAD

**Issue by MySt1k** [tcooc/AdditionalPipesBC#122]
log: http://pastebin.com/6vFF8LhE
crash: http://pastebin.com/ntjar9hu

**Comment by MySt1k** [comment]
Fix in core

**Comment by NitroxydeX** [comment]
How do you fixed the HashMap Problem?

**Comment by MySt1k** [comment]
It was a long war with an error.
Here look:
https://prok.pw/gitlab/Prototik/KCauldron/issues/33

**Comment by NitroxydeX** [comment]
But what was the problem? Is it a Problem with Additional Pipes?

**Comment by MySt1k** [comment]
as it turned out, Additional Pipes was not being ... rather he was guilty only by loading chunks, and the problem was entirely in something else.

**Comment by NitroxydeX** [comment]
Okay. I have the same issue but I dont know how and when it happens.
