### ISSUE TITLE
Unable to display forced chunk boundaries in 4.5.2-hotfix1

### ISSUE THREAD

**Issue by mwoodward** [tcooc/AdditionalPipesBC#123]
After updating our server to 4.5.2-hotfix1, pressing F10 no longer displays the forced chunk boundaries.

**Comment by multiplemonomials** [comment]
Did you also update Buildcraft?

**Comment by mwoodward** [comment]
We updated to what was the latest BuildCraft at the time of updating
AdditionalPipes...v7.0.10.

I noticed that BuildCraft has moved to v7.0.11, is this issue resolved by
something in that release?


Regards,
Maceo

**Comment by multiplemonomials** [comment]
No, more likely it was broken by something in the new BC.

**Comment by multiplemonomials** [comment]
Actually, it turned out to be something else entirely.  Should be fixed in the next version.  Thanks for letting me know.
