### ISSUE TITLE
Controls GUI stretched past window border

### ISSUE THREAD

**Issue by shadowsyllvet** [tcooc/AdditionalPipesBC#125]
![image](https://cloud.githubusercontent.com/assets/8488699/8701534/e874b91e-2ad7-11e5-858e-028b4e98a3e8.png)

After checking all my mods this only happens with additional pipes installed.
Pretty sure its the length of the text string that does this

**Comment by multiplemonomials** [comment]
Should be fixed in the next version.  Can you make sure?

Thanks.

**Comment by shadowsyllvet** [comment]
I will update tonight and check back. I've been using small gui settings on 1080 resolution so I haven't noticed it lately

**Comment by multiplemonomials** [comment]
I'm going to assume that this is fixed.

**Comment by shadowsyllvet** [comment]
Yes it is OMG i'm sooo sorry! I completely forgot about this post. 26 days later...

**Comment by multiplemonomials** [comment]
Nah, It's OK.  In GitHub terms, that isn't very long to put something off :)
