### ISSUE TITLE
Gravity transport pipe crash

### ISSUE THREAD

**Issue by Tedyhere** [tcooc/AdditionalPipesBC#127]
When right clicking a gravity transport pipe with a wrench the game crashes.
Using 4.6.1 with any buildcraft compat wrench. Also happens with buildcraft wrench.
Using Buildcraft 7.0.20
http://pastebin.com/1PNkCLsc

**Comment by multiplemonomials** [comment]
Should be fixed in the next version.  Thanks for letting me know!
