### ISSUE TITLE
Switch Fluid Pipe

### ISSUE THREAD

**Issue by wi-ta** [tcooc/AdditionalPipesBC#132]
Heya Jamie
I found the switch pipe not working :-/
![switch fluid pipe](https://cloud.githubusercontent.com/assets/11215905/10773840/14556222-7cfe-11e5-8737-f3555f2b751b.PNG)

using:
additionalpipes-4.7.0
buildcraft-7.1.11
buildcraft-compat-7.1.2

**Comment by multiplemonomials** [comment]
Sorry this took so long.  Should be fixed in the new version.
