### ISSUE TITLE
Curse Download

### ISSUE THREAD

**Issue by Noobsloth** [tcooc/AdditionalPipesBC#133]
Hello,

I am trying to open up my modpack on the curse launcher. They require your mod to be on the curseforge website or to be on the 3rd party mod list that has an open license to redistribute. Either of those requirements have not been met so I cannot use your mod in their launcher.

Since your license is open, I have submitted you mod to them to attempt to get it added to the list. But it would be greatly appreciated if you would add your mod to the Curse forge database. (Or whatever you call it.)

Thank you for your time,

Noobsloth

**Comment by multiplemonomials** [comment]
Additional Pipes (by tcooc)  is already on their list.   Is there some reason that doesn't work?

**Comment by Noobsloth** [comment]
This was meant for Additional Builcraft Objects... I need sleep and google sheets needs to not give me the wrong hyperlink when I click on the cell.

Sorry for waisting your time.

**Comment by multiplemonomials** [comment]
It's ok.

**Comment by Noobsloth** [comment]
Delete this? So I can hide my shame. XD
