### ISSUE TITLE
No background texture on Jeweled Pipe

### ISSUE THREAD

**Issue by permdaddy** [tcooc/AdditionalPipesBC#134]
![2015-12-26_13 50 28](https://cloud.githubusercontent.com/assets/9705945/12007556/f2ac4f74-abd7-11e5-8cb5-5d51c07e9fc7.png)

**Comment by multiplemonomials** [comment]
Which version are you using?

**Comment by permdaddy** [comment]
4.7.0

The latest version.

**Comment by multiplemonomials** [comment]
That's really weird.  I just tried it on a clean Minecraft install, and it works fine for me.  What Forge version are you using.  Is this a modpack?

**Comment by permdaddy** [comment]
Forge 1558

It's a private modpack.
Here is the modlist:
http://pastebin.com/tZqPAnPc

The modpack is unlisted on Technic if you want to see for yourself.
http://www.technicpack.net/modpack/perm-pack.783222

If you need any other info just let me know.

**Comment by multiplemonomials** [comment]
Could you send me your fml-client-latest.log please?

**Comment by multiplemonomials** [comment]
Never mind that.  I was testing with the new version I just built, v4.7.1.  For some reason, it only happens in 4.7.0.

Let's see here...

**Comment by permdaddy** [comment]
https://dl.dropboxusercontent.com/u/59240/fml-client-latest.log

The only one I have is from an updated version of the modpack so some of the mods are different, but the issue is the same.

**Comment by multiplemonomials** [comment]
Yup, for some reason the texture file was named incorrectly inside the jar.  I thought I fixed that! I'll upload a fixed version, or you can just download the new release.

**Comment by permdaddy** [comment]
Thank you.
