### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by jonnyplayer** [tcooc/AdditionalPipesBC#135]
Sorry,

im not sure if i am right here, but i found a problem with Additional Pipes and BuildCraft Compat.

I tryed using BuildCraft 7.1.14, Compat 7.1.3, AdditionalPipes 4.7.1 and some other Mods.
Minecraft crashes

But when i use exactly the same mods exept from AdditionalPipes 4.7.1 but AdditionalPipes 4.6.1 insteat, it works...

And if i put Compat away its works too...

Please Fix this error

P.S.: Sorry for my bad english...

**Comment by multiplemonomials** [comment]
Can you send me the crash log please?

**Comment by jonnyplayer** [comment]
I have fixed the problem, by reinstalling the mod...
Sorry that i have not anwered.
But thank you for trying to help me!

**Comment by multiplemonomials** [comment]
No problem.  Sorry it took so long for me to respond.
