### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nikita488** [tcooc/AdditionalPipesBC#136]
Crashlog:
http://pastebin.com/YacVLeka
Modlist:
![modlist](https://cloud.githubusercontent.com/assets/6237881/12742221/d6bbc0a8-c994-11e5-8a58-6c1202b2cd8c.PNG)

**Comment by multiplemonomials** [comment]
Try adding CoFH Core

**Comment by multiplemonomials** [comment]
Did that help?

**Comment by nikita488** [comment]
Yes! Thanks :)

**Comment by multiplemonomials** [comment]
Great.
