### ISSUE TITLE
Crash :(

### ISSUE THREAD

**Issue by MorcCrafak** [tcooc/AdditionalPipesBC#137]
Log : http://pastebin.com/iCpwW5z2

**Comment by multiplemonomials** [comment]
If it's not too much trouble, could you send me your world and what you did to get this crash?

**Comment by MorcCrafak** [comment]
[New World_rename_to_rar.zip](https://github.com/tcooc/AdditionalPipesBC/files/120830/New.World_rename_to_rar.zip)

**Comment by multiplemonomials** [comment]
Well _that_ was a simple fix.  Strangely enough though, while I was never able to get the logistics teleport pipe to work, somehow you've managed to. This crash is just a little copy-paste error which had never been triggered. Try [this version](https://dl.dropboxusercontent.com/u/27566023/Software%20Host/additionalpipes-4.7.2-test1.jar) and see how it works.

**Comment by MorcCrafak** [comment]
It crashed everytime on 4.7.1 but it seems to be working on 4.7.2-test1. Thanks!

**Comment by multiplemonomials** [comment]
So is the logistics teleport pipe actually transferring items?

**Comment by MorcCrafak** [comment]
I still need to use teleportation pipe. Basic pipes are red and not connected with these in my house.It gets sucked into the basic pipes and its goes nowhere

**Comment by multiplemonomials** [comment]
Yeah, I have the same problem and I can't figure out why.

**Comment by multiplemonomials** [comment]
Anyway, it seems like _this_ bug is fixed now.  Thanks for your help.
