### ISSUE TITLE
Teleport Power Pipes

### ISSUE THREAD

**Issue by KR4NK3NSCHW3ST3R** [tcooc/AdditionalPipesBC#140]
No Energy is beeing transported (Version 4.7.1 & 4.7.2)
Using buildcraft 7.1.14 & 7.1.15

**Comment by multiplemonomials** [comment]
Do you mind taking screenshots of the GUIs of the sending and recieving pipes please?

**Comment by KR4NK3NSCHW3ST3R** [comment]
![2016-03-21_17 28 47](https://cloud.githubusercontent.com/assets/6633025/13926036/e117dec6-ef8a-11e5-8d47-cac6060d03ab.png)
![2016-03-21_17 28 54](https://cloud.githubusercontent.com/assets/6633025/13926038/e11c82d2-ef8a-11e5-98dd-991d269cc062.png)
![2016-03-21_17 29 08](https://cloud.githubusercontent.com/assets/6633025/13926037/e11ab13c-ef8a-11e5-8f95-73352d27098d.png)

**Comment by Pilad** [comment]
Red - input. Blue - input.

**Comment by KR4NK3NSCHW3ST3R** [comment]
@Pilad: You are absolutely right. But it wont Transport Power!

**Comment by multiplemonomials** [comment]
Sorry, due to finals and a robotics competition, I can't work on this for at least another week.

**Comment by uptlak** [comment]
hello, I want to know what is the mod, that show you tooltips about blocks?
Thank you

**Comment by multiplemonomials** [comment]
It's called WAILA (What I am Looking At).  It's an addon for NEI.

**Comment by uptlak** [comment]
Thank you, I already installed this to my modpack, but if I aim to grass block I only get information that is caled Grass block and it is from Minecraft. How you enable additional information like harvestable or effective tool?

**Comment by multiplemonomials** [comment]
OK, it looks like buildcraft conductive pipes aren't able to extract energy from Thermal Expansion energy cells, period.  That's a buildcraft bug.  However, the normal buildcraft pipes are able to _input_ energy, so the teleport pipe is broken in that respect.

**Comment by multiplemonomials** [comment]
Oh wait, whoops.  The energy cells work, they just need wooden pipes in order to send energy to a conductive pipe network.

**Comment by multiplemonomials** [comment]
Actually, on closer inspection, Power Teleport Pipes have never had the capability to transmit directly to machines.  The code only sends power to other pipes.  I have now added this capability in the new version.
