### ISSUE TITLE
Teleport Pipe Access 

### ISSUE THREAD

**Issue by Lovinurmomma** [tcooc/AdditionalPipesBC#141]
So recently I discovered that Once a teleport pipe GUI of any kind Item/Fluid/Power has been accessed by a user no other users are able to access the GUI. So for instance If I place a teleport pipe and access the GUI to configure its settings no other user can access that teleport pipes GUI regardless if it is set to public or not. In the past there was no issue accomplishing this. Is this normal behavior now or some sort of Bug?

I have these versions of Minecraft/Mods installed

Minecraft 1.7.10
Forge 1.7.10-10.13.4.1614
[1.7.10]Better_Furnaces_V4.3
additionalpipes-4.7.2
appliedenergistics2-rv2-stable-10
archimedesshipsplus-1.7.10-1.8
BiblioCraft[v1.11.4][MC1.7.10]
BiblioWoods[BiomesOPlenty][v1.9]
BiomesOPlenty-1.7.10-2.1.0.1826-universal
buildcraft-7.1.16
buildcraft-compat-7.1.4
Carpenter's Blocks v3.3.7 - MC 1.7.10
ChestTransporter-2.0.3-MC1.7.10
Chisel-2.9.4.10
CodeChickenCore-1.7.10-1.0.7.47-universal
CoFHCore-[1.7.10]3.1.1-324
CompactSolars-1.7.10-4.4.37.314-universal
EnchantingPlus-1.7.10-3.0.2-d
forestry_1.7.10-4.2.7.55
GraveStones-1.7.2_1.4
industrialcraft-2-2.2.811-experimental
ironchest-1.7.10-6.0.62.742-universal
Mantle-1.7.10-0.3.2b
MapWriter-1.7.10-2.1.9
MCA-1.7.10-5.1.1.2-universal
movingworld-1.7.10-1.8
MrCrayfishFurnitureModv3.4.8(1.7.10)
MultiPageChest-1.3.2-MC1.7.10
neiaddons-1.12.14.40-mc1.7.10
NEIIntegration-MC1.7.10-1.1.1
NotEnoughItems-1.7.10-1.0.5.120-universal
OnlySilver-1.9.4-1.7.2
parachutemod-1.7.10-2.5.6-01
ProjectRed-1.7.10-4.7.0pre12.95-Base
ProjectRed-1.7.10-4.7.0pre12.95-Compat
ProjectRed-1.7.10-4.7.0pre12.95-Fabrication
ProjectRed-1.7.10-4.7.0pre12.95-Integration
ProjectRed-1.7.10-4.7.0pre12.95-Lighting
RadixCore-1.7.10-2.1.1-universal
Railcraft_1.7.10-9.8.0.0
RandomThings-2.2.4
RopeBridge-v1.3-mc1.7.10
TConstruct-1.7.10-1.8.8
ThermalExpansion-[1.7.10]4.1.2-240
ThermalFoundation-[1.7.10]1.2.3-112
Waila-1.5.10_1.7.10

**Comment by multiplemonomials** [comment]
No, this is definitely a bug.

**Comment by multiplemonomials** [comment]
Fixed in the next 1.7 version
