### ISSUE TITLE
Mod license?

### ISSUE THREAD

**Issue by rmtworks** [tcooc/AdditionalPipesBC#142]
Hi there! I looked through this fork as well as the original mod, and couldn't find a license for the mod. Could you point me in the right direction? Can this mod be used in public modpacks? Thanks!

**Comment by multiplemonomials** [comment]
Pubic modpacks are fine.  See [the archived forum thread](https://web.archive.org/web/20150919105906/http://mod-buildcraft.com/forums/showthread.php?tid=1467).

**Comment by rmtworks** [comment]
Thanks a bunch!
