### ISSUE TITLE
collision with NEI

### ISSUE THREAD

**Issue by uptlak** [tcooc/AdditionalPipesBC#144]
Hello, I find issue.

The newest version of Additional Pipes (4.7.2) collide with newest version of NEI (1.0.5.120)
without NEI game load without problem and everything works fine.
After I install NEI, game crash during loading.

I am using:

Minecraft: 1.7.10
newest Forge: 10.13.4.1614
newest BuildCraft: 7.1.16
newest BuildCraft compat: 7.1.5
newest Additional Pipes: 4.7.2
newest CodeChickenCore: 1.0.7.47
newest NotEnoughItems: 1.0.5.120

I am using these mods: BuildCraft with compat, Logistic Pipes, Additional Buildcraft Objects and I want to use additional Pipes and also NEI for recipes.

But I note another interesting issue. When I use all these mods, game crash during loading.
After I remove Additional Pipes, game load without problem. After I again try to add Additional Pipes game again crash during loading. 

But if I remove Logistic Pipes, game load without any problem, also with NEI and Additional Pipes.

So I think Additional Pipes mod has problem and collision with NEI and also maybe with Logistic Pipes.

I have only one solution, play without this amazing Additional Pipes mod :(

I hope you can help me with this problem.

Crash report:

> ---- Minecraft Crash Report ----
> // Why is it breaking :(
> 
> Time: 6/19/16 12:35 AM
> Description: There was a severe problem during mod loading that has caused the game to fail
> 
> cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: buildcraft/transport/TileGenericPipeCompat
> 	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
> 	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
> 	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
> 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
> 	at net.minecraft.client.main.Main.main(SourceFile:148)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> Caused by: java.lang.NoClassDefFoundError: buildcraft/transport/TileGenericPipeCompat
> 	at java.lang.Class.getDeclaredConstructors0(Native Method)
> 	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
> 	at java.lang.Class.getConstructor0(Unknown Source)
> 	at java.lang.Class.newInstance(Unknown Source)
> 	at buildcraft.core.CompatHooks.getBlock(CompatHooks.java:61)
> 	at buildcraft.BuildCraftTransport.preInit(BuildCraftTransport.java:340)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
> 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
> 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
> 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
> 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
> 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
> 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
> 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
> 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
> 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
> 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
> 	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
> 	... 10 more
> Caused by: java.lang.ClassNotFoundException: buildcraft.transport.TileGenericPipeCompat
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	... 42 more
> Caused by: java.lang.NoClassDefFoundError: cofh/api/transport/IItemDuct
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(Unknown Source)
> 	at java.security.SecureClassLoader.defineClass(Unknown Source)
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
> 	... 44 more
> Caused by: java.lang.ClassNotFoundException: cofh.api.transport.IItemDuct
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	... 48 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.7.10
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_91, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 172272872 bytes (164 MB) / 355590144 bytes (339 MB) up to 3207856128 bytes (3059 MB)
> 	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
> 	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 17 mods loaded, 17 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
> 	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
> 	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
> 	UCH	da3dsoulASMFix{0.1.0} [DA3DSOUL ASM Fixes] (minecraft.jar) 
> 	UCH	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
> 	UCH	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
> 	UCH	BuildCraft|Core{7.1.16} [BuildCraft] (buildcraft-7.1.16.jar) 
> 	UCH	BuildCraft|Builders{7.1.16} [BC Builders] (buildcraft-7.1.16.jar) 
> 	UCE	BuildCraft|Transport{7.1.16} [BC Transport] (buildcraft-7.1.16.jar) 
> 	UCH	BuildCraft|Energy{7.1.16} [BC Energy] (buildcraft-7.1.16.jar) 
> 	UCH	BuildCraft|Silicon{7.1.16} [BC Silicon] (buildcraft-7.1.16.jar) 
> 	UCH	BuildCraft|Factory{7.1.16} [BC Factory] (buildcraft-7.1.16.jar) 
> 	UCE	Additional-Buildcraft-Objects{MC1.7.10-BC7.1release4.0.9} [Additional Buildcraft Objects] (ABO-MC1.7.10-BC7.1release4.0.9.jar) 
> 	UCH	BuildCraft|Robotics{7.1.16} [BC Robotics] (buildcraft-7.1.16.jar) 
> 	UCE	LogisticsPipes{0.9.3.125} [Logistics Pipes] (logisticspipes-0.9.3.125.jar) 
> 	UCH	additionalpipes{4.7.0} [Additional Pipes] (additionalpipes-4.7.2.jar) 
> 	UCH	BuildCraft|Compat{7.1.5} [BuildCraft Compat] (buildcraft-compat-7.1.5.jar) 
> 	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.39' Renderer: 'GeForce GTX 970/PCIe/SSE2'

**Comment by multiplemonomials** [comment]
Have you installed CoFH Core?

**Comment by uptlak** [comment]
Thanks for your help, I forgot to install CoFH Core. Now everything works properly and run fine.
