### ISSUE TITLE
AdditionalPipes Crashes when loaded in server!

### ISSUE THREAD

**Issue by SteamPernk** [tcooc/AdditionalPipesBC#145]
I am running a 1.8.9 Forge Server, and when ever I put this mod in the mods folder, it crashes on start! Here's my crash log:

http://pastebin.com/W9Nw3Uhn

**Comment by SteamPernk** [comment]
I am using 3 other mods. BuildCraft, NotEnoughPotions, and PotionCore, which are all updated to the latest version. It crashes even if I only have BuildCraft and AdditionalPipes in the mods folder too!

**Comment by multiplemonomials** [comment]
Wow, I completely forgot to test server compatibility.  It should be fixed in the new release.  

Thanks for letting me know.  I'm glad at least one person is still watching this repository.

**Comment by multiplemonomials** [comment]
I'm closing this, because you haven't responded and I'm assuming that it's working.
