### ISSUE TITLE
Modpack Permissions

### ISSUE THREAD

**Issue by Tomstah** [tcooc/AdditionalPipesBC#147]
I would like to have modpack permissions for my modpack.

You can find it here
http://www.technicpack.net/modpack/quantonium-pack.860901

Thank you for reading.

**Comment by multiplemonomials** [comment]
As I say in my [forum thread](http://mod-buildcraft.com/forums/index.php?topic=157.0), I automatically grant all modpack permissions.  Feel free to use it.
