### ISSUE TITLE
Jeweled pipe missing GUI texture

### ISSUE THREAD

**Issue by zloibuka** [tcooc/AdditionalPipesBC#150]
In 4.7.2 all work fine, but in 4.3.3 jeweled pipe has no GUI. Can you fix it please?

MC 1.7.10, BC 7.1.18

upd: 

I found problem - its mistake in file name in assets\additionalpipes\textures\gui 

it must be "jeweledPipeGui.png", but now its "JeweledPipeGui.png".

**Comment by multiplemonomials** [comment]
Yep, it's the bug that keeps coming back because Git doesn't seem to track filename case changes.  It should be fixed now.  Can you redownload and test it again?

**Comment by zloibuka** [comment]
If you change filename in .jar - all should be ok, i just unpack .jar, decompile .class, find what name you use and what real name of file is and rename them, then pack again and all works.

But.. can you make pipes transparent when something pass in them, so i can see staff in pipe? I dont know how to do this :(

**Comment by multiplemonomials** [comment]
Should be fixed in the latest releases.
