### ISSUE TITLE
Adv. Wooden Transport Pipe cannot be crafted

### ISSUE THREAD

**Issue by AveoCross** [tcooc/AdditionalPipesBC#152]
Hi. I just noticed that I can't craft Advanced Wooden Transport Pipe. In NEI crafting recipe doesn't exist. After checking recipe (2 wooden gears and glass) in internet I cant craft this item. 
I'm using Additional Pipes version 4.7.5; BuildCraft Compat 7.1.5 and BuildCraft 7.1.19.

**Comment by multiplemonomials** [comment]
Should be fixed in the latest release
