### ISSUE TITLE
Broken with BoP-1.7.10-2.1.0.1889-universal.jar

### ISSUE THREAD

**Issue by chaos234** [tcooc/AdditionalPipesBC#154]
Hey,

your mod triggers something which breaks te hole part of BoP. I don't know why this is happen but is is triggered only with you mod so pls take a look on it and fix it, thanks.

Problem:

AntiIdConflict v1.3.5-1.7.10 checks for conflicting IDs such as potions, enchantments and also biomes.
If I put in your mod in my MP then BoP is no longer be able to override the vanilla biomes:

https://paste.ee/p/a9ADd

I don't know why this is caused and also I don't know why a chunkloading feature is needed (want a fully diable option for it pls) but smth. goes terribly wrong when BoP is be able to override vanilla bioms without your mod but not if your mod is present.

In addition here is the client log file and above the content from AntiIDConflict\biomes\conflictedIDs.txt

https://paste.ee/p/UKEFh

Most of the Startup-Errors can be ignored, important is the End of the file. I hope you'll find a solution for this, eventually adding BoP in the dependencies with an "after" flag but actually no chance to play with both together and no, I don't disable the vanilla biome override from biomegen.cfg because it is working fine and will otherwise destroy the world.

Hope that you can finde the problem.

**Comment by multiplemonomials** [comment]
hmmm I have no clue why this is happening

**Comment by multiplemonomials** [comment]
I will make a configuration option to completely disable the chunkloader in the next release.  Can you try that and see if it fixes the problem?

**Comment by multiplemonomials** [comment]
I do agree that the chunkloader seems like the only thing that has anything at all to do with Biomes O' Plenty

**Comment by chaos234** [comment]
I do agree with this. Actually I don't know why the chunkloader causes this problem because it should not interact with any worldgeneration because it only loads chunks (if not set to 0 in the config).

Eventually you can take a look at the code from the chickenchunks chunk/spot loader because they are loading chunks too but don't trigger any worldgenerror or smth. similar.

I think they are doing some ASM or they are waiting after all worldgen/biomechange is done and after that they are triggering the code behind the chunkloading. But think about that it should then not cause any error with chickenchunks chunkloader.

I am sure that there is a solution but it may not be that easy.

**Comment by multiplemonomials** [comment]
I didn't write the Additional Pipes chunkloader and it hardly needed any porting once I became the maintainer, so I honestly don't really know how it works.  I do know that it uses straight Forge API, no ASM or reflection.

**Comment by JarheadHME** [comment]
Have you been able to confirm that doing what you mentioned fixes it? If so would it be possible to release it? I'm currently playing with both BC and BoP and would love it if I was able to add this, but obviously currently it doesn't work.

**Comment by multiplemonomials** [comment]
Sorry, real life has been really busy lately.  I'll try to get a release out this weekend.

**Comment by JarheadHME** [comment]
Still no update on this?

**Comment by CarsonHoffman** [comment]
@JarheadHME it's not exactly a fix to the mod, but I saw this post (from 2015 even), and doing what it says ended up fixing it. I would try that out, just to see if it's a temporary fix for you too.

https://forum.feed-the-beast.com/threads/java-lang-arrayindexoutofboundsexception-118-unable-to-launch-ftb-infinity-version-2-0-2.129275/

**Comment by multiplemonomials** [comment]
Try the latest release

**Comment by JarheadHME** [comment]
Ended up having some other issues that prevented me from being able to try it for a long time. It doesn't seem to work though. The curse launcher when it tries to start says:
The game crashed whilst initializing game
Error: java.lang.ArrayIndexOutOfBoundsException: 118
However still starts up fine whenever I disable either biomes o' plenty or additional pipes.

[Here's the full crash report](https://pastebin.com/wYgiEBL3)

**Comment by multiplemonomials** [comment]
The crash comes from inside BoP.  Can ypu submit this as a bug report to them?

**Comment by JarheadHME** [comment]
They don't have support for anything that isn't the latest version anymore.

**Comment by multiplemonomials** [comment]
We seem to be at an impasse here, and there is a workaround at least.  I am closing this for now, as I am discontinuing support for 1.7
