### ISSUE TITLE
Teleport Pipes have no crafting recipe in Not enought items

### ISSUE THREAD

**Issue by adih2001** [tcooc/AdditionalPipesBC#155]
Hello,
I've added recently Additionalpipes to my server and modpack and i noticed that there is no crafting recipe for it in Not enought items.
http://i.imgur.com/0ptdGcv.png

Additionalpipes version: additionalpipes-4.7.6.jar
Buildcraft version: buildcraft-7.1.20.jar
Not enought items version: NotEnoughItems-1.7.10-1.0.5.120-universal.jar

EDIT: Forge version is 1614

**Comment by derwolfYT** [comment]
There is no recipe because BuildCraft NOT supports 
NEI by default, in 1.7.10 you have BCCompat
Recipe:
8 x Diamond Pipes
1 x Diamond Chipset
1 x Pulsating Chipset
10000 RF Or 1000MJ

**Comment by adih2001** [comment]
Ok thanks.
