### ISSUE TITLE
Can't craft Item Teleport Pipe

### ISSUE THREAD

**Issue by jingtongtangflee** [tcooc/AdditionalPipesBC#157]
I can't see crafting recipe for that pipe. I see only crafting from Fluid, Power and Logistics Teleport Pipe

**Comment by Ancieg** [comment]
The recipe is not visible, but it exists.(Sorry for bad English)
![screenshot_1](https://user-images.githubusercontent.com/29044775/27012159-73dc1346-4ed3-11e7-8f62-cd66e4395d5e.png)

**Comment by jingtongtangflee** [comment]
Got it. Thanks! :)
