### ISSUE TITLE
crash : teleport pipe error bug? 1.7.10

### ISSUE THREAD

**Issue by redfoxrommy** [tcooc/AdditionalPipesBC#163]
Hi :)
i was playing  world in tekkit legends. I was place a phase teleport pipe to my lp network than click to open its gui than game crash and ı can t reopen my save. other saves works fine. 

here is crash report :    http://paste.ubuntu.com/26214327/

can you solve the problem . tnx .

**Comment by multiplemonomials** [comment]
Sorry that happened!  The logistics pipe never really worked properly anyway, and was removed in a later version.  Please replace the additionalpipes jar in your modpack with the latest 1.7.10 version and the pipe should get deleted and your world should load.  

Alternately, you can enable "delete erroring tile entities" in your `forge.cfg` and your world should also load.

**Comment by redfoxrommy** [comment]
well tnx . its salvo the problem but is seems item teleport pipe not working. kenesis does . any way it is unimportend i take my save back . have a goog new year and tnx alot. :)
