### ISSUE TITLE
java.lang.NullPointerException: Ticking block entity at buildcraft.additionalpipes.pipes.PipeBehaviorTeleportPower.requestPower

### ISSUE THREAD

**Issue by kane-thornwyrd** [tcooc/AdditionalPipesBC#165]
[Crashlog](https://gist.github.com/kane-thornwyrd/70d8d1b0715d72590df57397682941e9)

Steps to reproduce:
- 1 mj teleport pipe set to send
- 3 set to recieve, freq 401
- set the send pipe to 401

**Comment by WrestGitHub** [comment]
[crash-2018-03-08_11.59.18-server.txt](https://github.com/tcooc/AdditionalPipesBC/files/1792461/crash-2018-03-08_11.59.18-server.txt)
my server is die :((
how fix that problem???

**Comment by multiplemonomials** [comment]
You guys were using the Power Teleport Pipe, weren't you... 

It doesn't actually work yet as the needed BuildCraft APIs haven't been added.  It was just in there as a placeholder, and I'm going to remove it in the next release.  

To fix your world, just edit forge.cfg and set `removeErroringTileEntities` to `true`/  That way, the next time you start the game, it will remove the crashing pipe.
