### ISSUE TITLE
too many logs

### ISSUE THREAD

**Issue by TOSUKUi** [tcooc/AdditionalPipesBC#169]
Teleport pipe output too many logs.
It output per fluid throw the pipe.

So I think It must decrease log output.
(e.g.) When critical problem caused or when pipe is set.

**Comment by TOSUKUi** [comment]
This problem occurred when use fluid pipe.
Version6.0.0.7

**Comment by multiplemonomials** [comment]
Have you tried turning off debug logging in `additionalpipes.cfg`?

**Comment by TOSUKUi** [comment]
Ok ill try it.
Thanks.

**Comment by Shadowrs** [comment]
Had the same issue. I created an [Issue on the BC](https://github.com/BuildCraft/BuildCraft/issues/4185#issuecomment-395337390) repo but that was the wrong place. I'll paste my description here for anyone reading in the future. 

`[01:30:51] [Server thread/INFO] [Additional Pipes]: [FluidTeleportPipe] Requested 0 MB of fluid
[01:30:51] [Server thread/INFO] [Additional Pipes]: [FluidTeleportPipe] Got 8920 MB of fluid
[01:30:51] [Server thread/INFO] [Additional Pipes]: PipeLiquidsTeleport's PreMoveToCentre event handler requested more fluid than can be handled!  8920 MB is left and will be rejected.
[01:30:51] [Server thread/INFO] [Additional Pipes]: [FluidTeleportPipe] Requested 0 MB of fluid
[01:30:51] [Server thread/INFO] [Additional Pipes]: [FluidTeleportPipe] Got 8920 MB of fluid
[01:30:51] [Server thread/INFO] [Additional Pipes]: PipeLiquidsTeleport's PreMoveToCentre event handler requested more fluid than can be handled!  8920 MB is left and will be rejected.`

Steps to reproduce: Add 6 point-to-point Fluid Teleport Pipes, have pipes fill up with liquid (destination tank or engine is full) and the INFO log level message is printed 10+ times per second. This eventually fills up the MC Server GUI text pane and after 1h30 (keep in mind my pc is brand new 8700k 16GB DDR4) it causes major server lag and eventually requires a server restart. Can be avoided by using the "nogui" option, where windows cmd output buffer is limited and messages are quickly discarded.

Additional information: Not a mem leak based on the server not exceeding 2GB ram, it's just the buffer of the GUI getting too large. Also I've actually destroyed all my fluid pipes and I'm still getting the message. I don't believe I've forgotten about a pipe somewhere. Is there a way to flush the Additional Pipes system or dump pipe locations? Thanks for reading!

**Comment by multiplemonomials** [comment]
You can always just uninstall the mod, start the server, then reinstall it.  That will delete all additionalpipes blocks.

What BC version are you using?  I might be able to do a quick hotfix right now

**Comment by Shadowrs** [comment]
BuildCraft version: 7.99.17 (& bc compat 7.99.14)
Forge version: forge-1.12.2-14.23.4.2705-universal @multiplemonomials 
Thanks for the reply

**Comment by multiplemonomials** [comment]
oh wait yeah, I almost forgot!  Since ages ago (before my time), Additional Pipes has had a console command for finding the locations of pipes!  Try this:
```
/additionalpipes teleport fluids
```

**Comment by Shadowrs** [comment]
Possibly useful info - I had 1 liquid tele pipe I forgot about. It was sending Lava from a pump into 3xtanks stacked on top of each other. I then had a wooden liquid pipe taking lava out of the bottom one, then going up 2x pipes on the side of the tank which means it was going in circles back to the tank before reaching a IC2 geothermal generator. This loop might have caused this spam

**Comment by multiplemonomials** [comment]
Alright, debug logging is turned off in the newest version (v6.0.0.8)
