### ISSUE TITLE
I cannot make power teleport pipes in 1.12.2 

### ISSUE THREAD

**Issue by rirubear** [tcooc/AdditionalPipesBC#170]
Is there any recipes for power teleport pipes?

**Comment by multiplemonomials** [comment]
No, they haven't been re-added yet.  The current BC8 power system does not support power teleport pipes, so I'm still waiting for Buildcraft to come out with its new power system.  From the looks of things, it will be a few months at least.

**Comment by Shadowrs** [comment]
For anybody looking for power teleportation in the mean time, here is a functional way to power a quarry remotely using 1.12.2 mods. 

- Power generation: Combustion Engines from BC 7.99 - consumes Fuel, produces MJ
- Energy Storage: Energy Storage Module from Galacticraft Core - accepts MJ, stores internally as gJ
- Power teleportation: Powercell from RFTools - powercell at each end, multiple can link on the same frequency, internal buffer is accumulative. 5 powercells = 5 * 1M RF = 5M RF. Accepts gJ from the storage module and converts to RF
- Consumer: Quarry from BC - consumes RF [Redstone Flux] from the powercell

![](https://i.imgur.com/RIehzIm.png)

Mods used:
- rftools-1.12-7.54
- GalacticraftCore-1.12.2-4.0.1.181
- buildcraft-7.99.17
- any coremods/libs that are required by the above mods

As a side note, a google search for methods of power teleportation will lead you to [Energy Tesseract from Thermal Expansion 3](https://ftbwiki.org/Energy_Tesseract) however this appears removed in TE5 for 1.12.2
