### ISSUE TITLE
CurseForge release

### ISSUE THREAD

**Issue by SanityCh3ck** [tcooc/AdditionalPipesBC#171]
Please consider making this mod available on CurseForge, ideally including the most important older versions. As it is now, you have to go through some trouble to find this repo, and it's only by chance that any new user could even stumble upon this mod's existence.

**Comment by multiplemonomials** [comment]
You're right, I've put it off for too long.

CurseForge page created! https://minecraft.curseforge.com/projects/additional-pipes-for-buildcraft?gameCategorySlug=mc-mods&projectID=302569
