### ISSUE TITLE
Item teleport pipe's recipe

### ISSUE THREAD

**Issue by sfchipan** [tcooc/AdditionalPipesBC#173]
In Minecraft1.12.2, BC is seemed to deleted the pulsating chipset's recipe. So what is the item teleprot pipe ‘s recipe now? Is it had another recipe?

**Comment by multiplemonomials** [comment]
I posted a screenshot of the recipe on the CurseForge thread: https://minecraft.curseforge.com/projects/additional-pipes-for-buildcraft?gameCategorySlug=mc-mods&projectID=302569
