### ISSUE TITLE
Can not craft teleport pipe in MC1.12.2

### ISSUE THREAD

**Issue by BlueNine9** [tcooc/AdditionalPipesBC#175]
AP version: 6.0.0.7
BC version: 7.99.17
BC removed pulsating chipset in this version(the latest version), so I'm not able to craft teleport pipe.

**Comment by multiplemonomials** [comment]
Wait, what?  Oh crap!  I'll try to get a fix out when I have time.

**Comment by multiplemonomials** [comment]
As it turns out, I already fixed this, but forgot about it.  The new recipe uses a Diamond Chipset and a Quartz Chipset along with the Diamond Pipes.  I posted a picture of the new recipe on the CurseFOrge page: https://minecraft.curseforge.com/projects/additional-pipes-for-buildcraft
