### ISSUE TITLE
Cant use this mod on tekkit lite theres an error with pipeItemsStripes.id

### ISSUE THREAD

**Issue by KOoRnFLaKes** [tcooc/AdditionalPipesBC#176]
I:pipeItemsStripes.id=31743

**Comment by multiplemonomials** [comment]
Can you post a bit more of the error message?  A pastebin of the FML client log would be helpful.

**Comment by multiplemonomials** [comment]
I'm sorry but I don't provide support for AP versions for game versions older than MC1.7.10
