### ISSUE TITLE
Teleport pipes broken cross-dimension

### ISSUE THREAD

**Issue by sharkck** [tcooc/AdditionalPipesBC#180]
I just setup a lava pump in the nether and setup a teleport pipe to send to a receiving pipe in dim 0 and nothing is coming through.  The pipes show connected.

MC Version 1.12.2 and APB version 6.0.0.8

**Comment by sharkck** [comment]
Nevermind I'm an idiot... (I think)...   I assumed that the teleport pipes chunkloaded... if they're supposed to then there be an issue.  I believe I remember reading something on the Wiki about the chunkloading is a known issue so... feel free to close if they're not supposed to chunkload!


Sorry!

**Comment by multiplemonomials** [comment]
Nope, they aren't supposed to chunkload themselves!  Older versions of Additional Pipes did offer a chunkloader, but it was always a separate block.
