### ISSUE TITLE
Teleport pipes

### ISSUE THREAD

**Issue by Juanserr** [tcooc/AdditionalPipesBC#181]
Hi, when i left click on a teleport pipe, it dont show me frequency's menu.
I'm on buildcraft 7.99.14, maybe I need a new version or something? In that case, if i will change BC's version, I would lost my things in a server? I can change buildcraft's version in the server by a new one
Sorry for my english...

**Comment by multiplemonomials** [comment]
Don't you need to right-click on it?

**Comment by multiplemonomials** [comment]
Yes, please retry with the latest version of BC.

**Comment by multiplemonomials** [comment]
Any luck?

**Comment by Juanserr** [comment]
Sorry for not answer before.
Ye it was BC's version. Thank you for your help

**Comment by multiplemonomials** [comment]
No prob!
