### ISSUE TITLE
Missing power teleport pipe

### ISSUE THREAD

**Issue by popos123** [tcooc/AdditionalPipesBC#182]
Like in title,
And i don't understand the explanation:

Q: What happened to the Redstone Pipe? 
A: It has been removed because it duplicated features provided by Gates.  If you haven't used them, give them a try!

MC: 1.12.2, AP: 6.0.0.8, Forge: 14.23.4.2705

(Like in this old topic: https://github.com/tcooc/AdditionalPipesBC/issues/170)

**Comment by multiplemonomials** [comment]
The Power Teleport Pipe hadn't been re-added yet in the 1.12 version because Buildcraft hasn't released the APIs necessary for me to add it.  Hopefully, by the time BC gets a stable release, I'll have what I need to re-add it.

**Comment by lildevuwu** [comment]
Any new info? BC still doesn't have API for kinesis pipes in 1.12.2?
