### ISSUE TITLE
Crash when adding to Sevtech Ages 3.0.8

### ISSUE THREAD

**Issue by ReportBot9009** [tcooc/AdditionalPipesBC#183]
Hello, 

I added this mod to Sevtech 3.0.8 and partly way through loading the modpack, there is a nullpointer crash.  This is on a working instance that I've lightly added other mods to.

i7 4790
GTX 1080
32GB RAM
500GB EVO
Java 1.87.0_181
7168MB allocated

Optifine/SEUS added if that's a problem

Crash Report: https://paste.ee/p/QZCGr
MultiMC Upload Log: https://paste.ee/p/b0AhS

**Comment by multiplemonomials** [comment]
Hmm I'm not sure AdditionalPipes is involved in this at all, actually.  From the following line, it looks like the crash is coming from Better with Addons, or possibly from Buildcraft Silicon:
```
Caused by: java.lang.NullPointerException
	at betterwithaddons.block.EriottoMod.BlockZenSand.func_180651_a(BlockZenSand.java:68)
	at buildcraft.silicon.plug.FacadeStateManager.getRequiredStack(FacadeStateManager.java:202)
	at buildcraft.silicon.plug.FacadeStateManager.init(FacadeStateManager.java:266)
	at buildcraft.silicon.BCSilicon.init(BCSilicon.java:73)
```

**Comment by ReportBot9009** [comment]
That's the interesting part. This crash only happens when I add additional pipes. Otherwise, no other problems.

**Comment by multiplemonomials** [comment]
Huh, that's strange, but you really might want to report this to Better With Addons, since the crash is happening in their code.
