### ISSUE TITLE
Teleportation pipes

### ISSUE THREAD

**Issue by teodortomas** [tcooc/AdditionalPipesBC#202]
Hello, i have a problem, sometimes the teleportation pipes are not visible in recipes list. When I am trying to use them they are not going to link, one of a 100 tries i got it linked... Will this mod be fixed? Thanks

**Comment by multiplemonomials** [comment]
I'll be honest, I'm not really actively developing this mod anymore, I haven't done any minecraft stuff in a year or two

**Comment by teodortomas** [comment]
> I'll be honest, I'm not really actively developing this mod anymore, I haven't done any minecraft stuff in a year or two

That is really a shame, but i get it... It's just wierd that there is no other mod with features like this one.

**Comment by multiplemonomials** [comment]
fwiw, this repo only covers the mod from MC1.7 to MC1.12.  I didn't even work on versions of the mod before MC1.7.

**Comment by xJon** [comment]
If they were referring to Tekkit 2 it's on Minecraft 1.12.2.

**Comment by teodortomas** [comment]
> Are you playing Tekkit 2? (If so, they have been hidden because of the duping & chunk loading issues reported here)

I am playing "The 1.12.2 pack"

**Comment by redman6973** [comment]
I'm also playing The 1.12.2 Pack but I've tried on both multi and singleplayer to find the recipe in NEI but the item won't show up. I'm not sure if it's just an NEI bug, but I'm using the latest version of Additional Pipes (6.0.0.8) and Buildcraft (7.99.24.8) 

I have not progressed far enough to find out if I can still craft the pipe but so far it is impossible to spawn it in creative.
Just thought I'd post in case I'm not the only one.
![2022-12-25_00 52 14](https://user-images.githubusercontent.com/85704618/209458301-063f4316-0615-4bef-8790-6c57d958f9a9.png)

**Comment by xJon** [comment]
@redman6973 They are hidden in JEI due to issues.

**Comment by redman6973** [comment]
> @redman6973 They are hidden in JEI due to issues.

okay, makes sense. they're still craftable?

**Comment by xJon** [comment]
@redman6973 Yes :)

**Comment by jdavis739** [comment]
how do I craft them? I put the parts in the workbench but it won't create it and the cheat menu won't show them. Do I have to edit one of the mod's files for tekkit 2?

**Comment by xJon** [comment]
@jdavis739 It's better if you can open an issue over the modpack's repo (https://github.com/xJon/The-1.12.2-Pack/issues/) instead of commenting here :)
