### ISSUE TITLE
Enhanced Diamond Pipe idea

### ISSUE THREAD

**Issue by amorek** [tcooc/AdditionalPipesBC#80]
New pipe that would sort things based on Forge's ore dictionary, for example if I put wooden log in blue filter, all kinds of wooden logs would go in blue output.

**Comment by multiplemonomials** [comment]
Now that your issue has been closed on that tracker, I'm re-opening it here.  I'm thinking of making the Jeweled Pipe, which would have 30 slots per direction and could match by NBT, durability, and the ore dictionary.

**Comment by multiplemonomials** [comment]
Finally done!
