### ISSUE TITLE
graphic glitch in modpack

### ISSUE THREAD

**Issue by zortag** [tcooc/AdditionalPipesBC#97]
2.4.5b

textures can't load in DNS modpack from ATLauncher (whit resource pack too)
i tryied to export it from the jar and put it in a resource pack and use an external skin pack (sphax). i checked the folder tree.
with no resource pack all pipes and block appear invisible, with the resource pack all pipes uses the same (wrongh) skin

**Comment by multiplemonomials** [comment]
It's been a while, huh.  Do you have any objections to me closing this, or do you still have the non-working modpack set up so we can troubleshoot it?

**Comment by multiplemonomials** [comment]
Closed due to inactivity.
